- id: auto_accent_lights_on
  alias: 'Turn on accent lights at sunset'
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: light.turn_on
      entity_id: light.tv_backlight
    - service: switch.turn_on
      entity_id: switch.bar_accent_light

- id: auto_accent_lights_off
  alias: 'Turn off accent lights at sunrise'
  trigger:
    - platform: sun
      event: sunrise
  action:
    - service: light.turn_off
      entity_id: light.tv_backlight
    - service: switch.turn_off
      entity_id: switch.bar_accent_light
