homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret http_base_url
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.0.0/24
  ip_ban_enabled: True
  login_attempts_threshold: 3

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - songpal

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# MQTT broker
mqtt:
  broker: !secret mqtt_server
  port: !secret mqtt_port
  username: !secret mqtt_user
  password: !secret mqtt_password

# disabled until auth bug is fixed
# https://github.com/home-assistant/home-assistant/issues/9143#issuecomment-339335401
# https://github.com/happyleavesaoc/python-myusps/issues/9
#usps:
#  username: !secret usps_username
#  password: !secret usps_password

device_sun_light_trigger:
  light_group: group.living_room_ambient_lights
  light_profile: relax
  device_group: group.people

google_assistant:
  project_id: !secret ga_project_id
  client_id: !secret ga_client_id
  access_token: !secret ga_access_token
  agent_user_id: !secret ga_agent_user_id
  api_key: !secret ga_api_key
  exposed_domains:
    - switch
    - light
    - group

emulated_hue:

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

group: !include_dir_merge_named group
automation: !include_dir_merge_list automation
script: !include scripts.yaml
sensor: !include_dir_merge_list sensor
light: !include lights.yaml
switch: !include switches.yaml
device_tracker: !include device_tracker.yaml
zone: !include zones.yaml
media_player: !include media_players.yaml
notify: !include notifications.yaml
camera: !include cameras.yaml
