- platform: tplink
  host: 192.168.0.160
  name: Bedroom Color

- platform: tplink
  host: 192.168.0.170
  name: Bedroom White

- platform: tplink
  host: 192.168.0.161
  name: Living Room Color

- platform: tplink
  host: 192.168.0.172
  name: Living Room Reading Light

- platform: tplink
  host: 192.168.0.171
  name: Living Room White

- platform: yeelight
  devices:
    192.168.0.180:
      name: TV Backlight

- platform: template
  lights:
    bar_accent_light:
      friendly_name: Bar Accent Light
      value_template: "{{ 'on' if is_state('switch.bar_accent_light', 'on') else 'off' }}"
      turn_on:
        - service: switch.turn_on
          entity_id: switch.bar_accent_light
      turn_off:
        - service: switch.turn_off
          entity_id: switch.bar_accent_light
