- platform: fedex
  username: !secret fedex_username
  password: !secret fedex_password
  name: FedEx

# Track battery level
- platform: mqtt
  state_topic: "owntracks/ryan/phone"
  name: "Ryan's Phone Battery Level"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'
- platform: mqtt
  state_topic: "owntracks/chelse/phone"
  name: "Chelse's Phone Battery Level"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'

- platform: speedtest
  minute: 30
  hour:
    - 0
    - 6
    - 12
    - 18
  monitored_conditions:
    - ping
    - download
    - upload

- platform: synologydsm
  host: 192.168.0.20
  port: 50000
  username: !secret synologydsm_username
  password: !secret synologydsm_password
  monitored_conditions:
    - cpu_total_load
    - memory_real_usage
    - network_up
    - network_down
    - volume_size_total
    - volume_size_used
    - volume_percentage_used

# Template sensor for Harmony Hub
- platform: template
  sensors:
    harmony_hub:
      value_template: '{{ states.remote.harmony_hub.attributes.current_activity }}'
      friendly_name: 'Harmony Hub'

- platform: ups
  username: !secret ups_username
  password: !secret ups_password
  name: UPS

# Weather prediction
- platform: yr
