# Track battery level
- platform: mqtt
  state_topic: "owntracks/ryan/phone"
  name: ryan_phone_mqtt_battery
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'

- platform: mqtt
  state_topic: "owntracks/chelse/phone"
  name: chelse_phone_mqtt_battery
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'

- platform: template
  sensors:
    ryans_phone_battery_level:
      friendly_name: "Ryan's Phone Battery Level"
      unit_of_measurement: '%'
      value_template: "{{ states('sensor.ryan_phone_mqtt_battery') }}"
      icon_template: >-
        {% set battery_level = states('sensor.ryan_phone_mqtt_battery') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}
    chelses_phone_battery_level:
      friendly_name: "Chelse's Phone Battery Level"
      unit_of_measurement: '%'
      value_template: "{{ states('sensor.chelse_phone_mqtt_battery') }}"
      icon_template: >-
        {% set battery_level = states('sensor.chelse_phone_mqtt_battery') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}
