- platform: template
  sensors:
    # Template sensor for Harmony Hub
    harmony_hub:
      friendly_name: 'Harmony Hub'
      value_template: >-
        {% if is_state('remote.harmony_hub', 'on') %}
          {{ states.remote.harmony_hub.attributes.current_activity }}
        {% endif %}
