- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - precip_intensity
    - precip_intensity_max
    - temperature
    - apparent_temperature
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - visibility
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_max
    - temperature_min
    - uv_index

# Moon phases
- platform: moon

- platform: wunderground
  api_key: !secret wunderground_api_key
  monitored_conditions:
    - observation_time
    - alerts
    - feelslike_f
    - heat_index_f
    - temperature_string
    - temp_high_record_f
    - temp_high_1d_f
    - temp_f
    - temp_low_1d_f
    - temp_low_record_f
    - precip_1d
    - precip_1d_in
    - wind_mph
    - wind_1d_mph
    - wind_degrees
    - wind_dir
    - wind_string
    - relative_humidity
    - solarradiation
    - UV
    - visibility_mi
    - weather
    - weather_1d
    - weather_1n
    - weather_2d
    - weather_2n
    - weather_3d
    - weather_3n
    - weather_4d
    - weather_4n

# Weather prediction
- platform: yr
